version: '3.8'
services:
  api:
    build: ./api
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_URLS=http://+:80
  web:
    build: ./web
    ports:
      - "3000:80"
    depends_on:
      - api
