name: CI/CD Pipeline

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      VITE_API_URL: ${{ vars.VITE_API_URL }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install dependencies
        run: cd web && npm ci
      - name: Run ESLint
        run: cd web && npm run lint

  build:
    runs-on: ubuntu-latest
    needs: lint
    env:
      VITE_API_URL: ${{ vars.VITE_API_URL }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install dependencies
        run: cd web && npm ci
      - name: Build frontend
        run: cd web && npm run build
      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.0.x"
      - name: Restore .NET dependencies
        run: cd api && dotnet restore
      - name: Build backend
        run: cd api && dotnet build --configuration Release --no-restore

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    env:
      VITE_API_URL: ${{ vars.VITE_API_URL }}
    steps:
      - uses: actions/checkout@v4

      # Package frontend
      - name: Generate frontend deployment package
        run: cd web && zip -r deploy.zip . -x '*.git*'

      # Package backend
      - name: Generate backend deployment package
        run: cd api && zip -r deploy.zip . -x '*.git*'

      # Deploy frontend
      - name: Deploy to Elastic Beanstalk (Web)
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: geotracker-web-env
          environment_name: geotracker-web-env
          version_label: ${{ github.sha }}-web
          region: us-east-1
          deployment_package: web/deploy.zip

      # Deploy backend
      - name: Deploy to Elastic Beanstalk (API)
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: geotracker-api
          environment_name: geotracker-api-env
          version_label: ${{ github.sha }}-api
          region: us-east-1
          deployment_package: api/deploy.zip
